imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@FrontProductBundle/Resources/config/services.yml" }
    - { resource: "@BackProductBundle/Resources/config/services.yml" }
    - { resource: "@FrontMarketingBundle/Resources/config/services.yml" }
    - { resource: "@FrontSavBundle/Resources/config/services.yml" }
    - { resource: "@FrontCartBundle/Resources/config/services.yml" }
    - { resource: "@FrontEventBundle/Resources/config/services.yml" }
    - { resource: "@FrontDeliveryBundle/Resources/config/services.yml" }
    - { resource: "@BackMarketingBundle/Resources/config/services.yml" }
    - { resource: "@BackCartBundle/Resources/config/services.yml" }
    - { resource: "@BackSavBundle/Resources/config/services.yml" }
    - { resource: "@BackDeliveryBundle/Resources/config/services.yml" }
    - { resource: "@BackEventBundle/Resources/config/services.yml" }


# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:

    #esi: ~
    default_locale: 'en'
    translator:
        fallbacks: ['en']

    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    #host: '%mailer_host%'
    username: dali alaya
    password: Dali1997
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: dalialaya2@gmail.com
        sender_name: Alaya dali
    registration:
        form:
            type: AppBundle\Form\RegistrationFormType
        confirmation:
            enabled: true
    from_email:
        address: dalialaya2@gmail.com
        sender_name: Alaya dali

    profile:
        form:
            type: AppBundle\Form\ProfileFormType
    resetting:
        email:
            from_email:
                address:        dalialaya2@gmail.com
                sender_name:    Alaya dali

hwi_oauth:
    connect:
        account_connector: my_user_provider
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           2328260830518343
            client_secret:       8e55634ba5f32012e7e2bcea4ad7df81
            scope:               email
            infos_url:           "https://graph.facebook.com/me?fields=email,first_name,last_name,name,picture.type(square),id"
            paths:
                email:       email
                firstname:   first_name
                lastname:    last_name
                profilepicture: picture
            options:
                display: popup
        google:
            type:                google
            client_id:           380362594092-lpeicp2rfgppqn3n67imins61osqm5o7.apps.googleusercontent.com
            client_secret:       nTnQTknfCMceeBRuUGJ133bC
            scope:              "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email:           email
                profilepicture:  picture
            options:
                display:     popup

